CREATE DATABASE EJERCICIO1_CLIENTES;
USE EJERCICIO1_CLIENTES;
CREATE TABLE CLIENTES (
	COD integer primary key auto_increment,
    NOMBRE VARCHAR (20),
	APELLIDOS VARCHAR(20),
    EDAD INT,
    CORREO VARCHAR(50) UNIQUE
);