CREATE DATABASE GESTOR_PROYECTOS;
USE GESTOR_PROYECTOS;
CREATE TABLE EMPLEADOS(
	DNI VARCHAR(9) UNIQUE PRIMARY KEY, 
    NOMBRE VARCHAR(40)
);
CREATE TABLE PROYECTOS(
	COD integer primary key auto_increment,
    NOMBRE VARCHAR(40) unique,
    DNI_EMP VARCHAR(9),
    F_INICIO DATE,
    F_FIN DATE
);
CREATE TABLE ASIG_PROYECTOS(
	DNI_EMP varchar(9),
    NUM_PROY int,
    F_INICIO DATE,
    F_FIN DATE
);